image:
  repository: 385595570414.dkr.ecr.us-west-2.amazonaws.com/dbaas/gardener/extensions/os-ubuntu-tikv
  tag: latest
  pullPolicy: Always

resources: {}

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []
